# Generated by Django 3.1.7 on 2021-04-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custid', models.AutoField(db_column='CustID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('type', models.IntegerField(db_column='Type', primary_key=True, serialize=False)),
                ('category', models.IntegerField(db_column='Category')),
                ('weekly', models.FloatField(blank=True, db_column='Weekly', null=True)),
                ('daily', models.FloatField(blank=True, db_column='Daily', null=True)),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(blank=True, db_column='StartDate', max_length=11, null=True)),
                ('orderdate', models.CharField(blank=True, db_column='OrderDate', max_length=11, null=True)),
                ('rentaltype', models.IntegerField(db_column='RentalType')),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('returndate', models.CharField(blank=True, db_column='ReturnDate', max_length=11, null=True)),
                ('totalamount', models.FloatField(blank=True, db_column='TotalAmount', null=True)),
                ('paymentdate', models.CharField(blank=True, db_column='PaymentDate', max_length=11, null=True)),
                ('returned', models.IntegerField(blank=True, db_column='Returned', null=True)),
            ],
            options={
                'db_table': 'rental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.CharField(db_column='VehicleID', max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=40, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('type', models.IntegerField(db_column='Type')),
                ('category', models.IntegerField(blank=True, db_column='Category', null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
